# Generated by Django 4.2.11 on 2025-11-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=64, unique=True)),
                ('zaner', models.CharField(choices=[('fps', 'FPS'), ('tps', 'TPS'), ('battleroyal', 'Battle Royale'), ('moba', 'MOBA'), ('rpg', 'RPG'), ('mmorpg', 'MMORPG'), ('survival', 'Survival'), ('openworld', 'Open World'), ('fighting', 'Fighting'), ('sports', 'Sports'), ('racing', 'Racing'), ('strategy', 'Strategy'), ('adventure', 'Adventure'), ('partygames', 'RPG'), ('card', 'Card'), ('simulator', 'Simulator')], max_length=64)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oznamenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(default='Notifikácia', max_length=255)),
                ('typ', models.CharField(choices=[('pozvanka', 'Pozvánka'), ('upozornenie', 'Upozornenie'), ('sprava', 'Správa')], default='sprava', max_length=15)),
                ('obsah', models.TextField()),
                ('datum_vytvorenia', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('uroven', models.IntegerField(default=1)),
                ('datum_registracie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rebricek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('tyzdenny', 'Týždenný'), ('mesacny', 'Mesačný'), ('rocny', 'Ročný')], max_length=64)),
                ('datum_aktualizacie', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov_role', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=64, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('uroven', models.IntegerField(default=1)),
                ('clenovia', models.ManyToManyField(related_name='timy_clenom_je', to='core.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Udalost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=64)),
                ('popis', models.TextField(blank=True, null=True)),
                ('datum_konania', models.DateField()),
                ('typ', models.CharField(choices=[('mission', 'Mission'), ('quest', 'Quest'), ('challange', 'Challange'), ('event', 'Event'), ('match', 'Match'), ('battle', 'Battle'), ('duel', 'Duel'), ('raid', 'Raid'), ('tournament', 'Tournament'), ('dungeon', 'Dungeon')], max_length=64)),
                ('hra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hra')),
                ('organizator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='udalosti_organizovane', to='core.profil')),
                ('ucastnici', models.ManyToManyField(blank=True, related_name='prihlasene_udalosti', to='core.profil')),
            ],
        ),
        migrations.AddField(
            model_name='profil',
            name='rola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rola'),
        ),
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Odoslanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_odoslania', models.DateTimeField(auto_now_add=True)),
                ('datum_precitania', models.DateTimeField(blank=True, null=True)),
                ('stav', models.CharField(choices=[('neprecitane', 'Neprečítané'), ('precitane', 'Prečítané')], default='neprecitane', max_length=64)),
                ('oznamenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.oznamenie')),
                ('prijemca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prijate_oznamenia', to='core.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Hodnotenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnotenie', models.IntegerField()),
                ('datum_hodnotenia', models.DateField(auto_now_add=True)),
                ('hra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hra')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profil')),
                ('udalost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.udalost')),
            ],
        ),
        migrations.CreateModel(
            name='Umiestnenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozicia', models.IntegerField()),
                ('body', models.IntegerField()),
                ('rebricek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rebricek')),
                ('tim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tim')),
            ],
            options={
                'unique_together': {('tim', 'rebricek')},
            },
        ),
        migrations.CreateModel(
            name='Priatelstvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stav', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('datum', models.DateField(auto_now_add=True)),
                ('profil1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziadost_odoslana', to='core.profil')),
                ('profil2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziadost_prijata', to='core.profil')),
            ],
            options={
                'unique_together': {('profil1', 'profil2')},
            },
        ),
        migrations.AddConstraint(
            model_name='hodnotenie',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('hra__isnull', False), ('udalost__isnull', True)), models.Q(('hra__isnull', True), ('udalost__isnull', False)), _connector='OR'), name='jedinecny_objekt_hodnotenia'),
        ),
    ]
