# Generated by Django 5.2.8 on 2025-11-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov_role', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('uroven', models.IntegerField(default=1)),
                ('datum_registracie', models.DateField(auto_now_add=True)),
                ('rola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rola')),
            ],
        ),
        migrations.CreateModel(
            name='Priatelstvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stav', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('datum', models.DateField(auto_now_add=True)),
                ('profil1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziadost_odoslana', to='core.profil')),
                ('profil2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziadost_prijata', to='core.profil')),
            ],
            options={
                'unique_together': {('profil1', 'profil2')},
            },
        ),
    ]
