# Generated by Django 4.2.11 on 2025-11-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebricek',
            name='typ',
            field=models.CharField(choices=[('denny', 'Denný'), ('tyzdenny', 'Týždenný'), ('mesacny', 'Mesačný')], max_length=64),
        ),
        migrations.AlterField(
            model_name='udalost',
            name='datum_konania',
            field=models.DateTimeField(),
        ),
    ]
