# Generated by Django 4.2.11 on 2025-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rebricek_typ_alter_udalost_datum_konania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udalost',
            name='ucastnici',
            field=models.ManyToManyField(blank=True, to='core.profil'),
        ),
    ]
