# Generated by Django 4.2.11 on 2025-11-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='udalost',
            name='ucastnici',
            field=models.ManyToManyField(blank=True, related_name='prihlasene_udalosti', to='core.profil'),
        ),
    ]
