# Generated by Django 4.2.11 on 2025-11-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_udalost_ucastnici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udalost',
            name='ucastnici',
            field=models.ManyToManyField(blank=True, related_name='prihlasene_udalosti', to='core.profil'),
        ),
    ]
