# Generated by Django 4.2.11 on 2025-11-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_udalost_ucastnici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oznamenie',
            name='nazov',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='oznamenie',
            name='typ',
            field=models.CharField(choices=[('pozvanka', 'Pozvánka'), ('upozornenie', 'Upozornenie'), ('sprava', 'Správa')], default='sprava', max_length=15),
        ),
    ]
