# Generated by Django 4.2.11 on 2025-11-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_udalost_ucastnici'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('od_koho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odoslane_ziadosti', to='core.profil')),
                ('pre_koho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prijate_ziadosti', to='core.profil')),
            ],
        ),
    ]
