# Generated by Django 4.2.11 on 2025-11-26 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_oznamenie_nazov_alter_oznamenie_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoslanie',
            name='datum_odoslania',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='odoslanie',
            name='datum_precitania',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oznamenie',
            name='datum_vytvorenia',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='oznamenie',
            name='nazov',
            field=models.CharField(default='Notifikácia', max_length=255),
        ),
        migrations.AlterField(
            model_name='profil',
            name='rola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rola'),
        ),
    ]
