# Generated by Django 4.2.11 on 2025-11-28 21:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priatelstvo',
            name='datum',
        ),
        migrations.AddField(
            model_name='priatelstvo',
            name='datum_vytvorenia',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priatelstvo',
            name='profil1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priatelstva_1', to='core.profil'),
        ),
        migrations.AlterField(
            model_name='priatelstvo',
            name='profil2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priatelstva_2', to='core.profil'),
        ),
        migrations.AlterField(
            model_name='priatelstvo',
            name='stav',
            field=models.CharField(choices=[('pending', 'Čakajúce'), ('accepted', 'Prijaté'), ('blocked', 'Blokované')], default='pending', max_length=20),
        ),
    ]
