# Generated by Django 4.2.11 on 2025-12-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_priatelstvo_datum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hra',
            name='zaner',
            field=models.CharField(choices=[('fps', 'FPS'), ('tps', 'TPS'), ('battleroyal', 'Battle Royale'), ('moba', 'MOBA'), ('rpg', 'RPG'), ('mmorpg', 'MMORPG'), ('survival', 'Survival'), ('openworld', 'Open World'), ('fighting', 'Fighting'), ('sports', 'Sports'), ('racing', 'Racing'), ('strategy', 'Strategy'), ('adventure', 'Adventure'), ('partygames', 'Party Games'), ('card', 'Card'), ('simulator', 'Simulator')], max_length=64),
        ),
        migrations.AlterField(
            model_name='oznamenie',
            name='nazov',
            field=models.CharField(default='Systémová správa', max_length=255),
        ),
        migrations.AlterField(
            model_name='udalost',
            name='typ',
            field=models.CharField(choices=[('mission', 'Mission'), ('quest', 'Quest'), ('challenge', 'Challenge'), ('event', 'Event'), ('match', 'Match'), ('battle', 'Battle'), ('duel', 'Duel'), ('raid', 'Raid'), ('tournament', 'Tournament'), ('dungeon', 'Dungeon')], max_length=64),
        ),
    ]
