# Generated by Django 4.2.11 on 2025-12-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hra_zaner_alter_oznamenie_nazov_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='umiestnenie',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='umiestnenie',
            name='rebricek',
        ),
        migrations.RemoveField(
            model_name='umiestnenie',
            name='tim',
        ),
        migrations.DeleteModel(
            name='Rebricek',
        ),
        migrations.DeleteModel(
            name='Umiestnenie',
        ),
    ]
